Project completed
dennis-every/stocks pull request #8
Opened 2023-03-15 12:58 UTC by dennis-every

This pull request is for review and approval to merge the dev branch into the main branch. The following tasks were completed:

- Project setup with create-react-app and linters
- Add routes and navigation with react-router
- Add Axios to fetch data from the API
- Add Redux store to retrieve and store the data
- Add tests with react-testing-library and Jest
- Add styles with bootstrap and react icons
- Deploy demo app on Render
- Add readme with a live link to the demo

2023-03-15 15:09 UTC, brytebee requested changes
Hi, @dennis-every👋, 

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Proper flow used for your version control.✔️
- App functions as it should.✔️
- Great video presentation. Bravo 👏👏👏
    - Good video length.✔️
    - Demos app and mentions the part you're proud of.✔️
- App is hosted and link is added to README.✔️


##

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes ♻️ 

<img src="https://media4.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification. 
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-15 15:09 UTC, brytebee commented on src/components/StocksContainer.jsx
This component is required to contain a way the user can search the data rendered. Kindly add this.

![image](https://user-images.githubusercontent.com/27709832/225349014-18092f74-8da4-4efa-a522-8ffef1c458d6.png) 

You could place this search box strategically in your design.

![image](https://user-images.githubusercontent.com/27709832/225349392-c7cd1b23-2dfe-4322-bd37-d841b4f6f0f7.png)

![image](https://user-images.githubusercontent.com/27709832/225349552-fa829404-4865-42c2-bfa5-c14153b977df.png)

2023-03-15 15:09 UTC, brytebee commented on src/components/StocksContainer.scss
You are required to keep to the design template given for the project.

There are inconsistencies in the render of your boxes and their dimensions. Kindly fix.

The `font-size` of the titles and figures varies, kindly take note and implement. 

**NOTE**
If the titles length affect the sizes of check design, you could `slice` them to be uniform throughout the page, then the whole title would be visible in the details page.


Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/225350834-abb5486b-d794-4094-9710-f5d02a8f1f91.png) | ![image](https://user-images.githubusercontent.com/27709832/225350362-f09b3bed-3a34-418a-8d95-585a5e3d1a76.png)

2023-03-17 17:36 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- All suggestions from the previous review are done! 👍 

### Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 17:45 UTC, dennis-every commented on src/components/StocksContainer.scss
Ok, tks for the feedback!

2023-03-17 17:45 UTC, dennis-every commented
Ok, tks for the feedback!

2023-03-17 17:46 UTC, merged

2023-03-20 15:46 UTC, Omar-Muhamad reviewed
# Approved ✔
### Hi @dennis-every,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).